# Generated by Django 4.1 on 2022-08-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelformsProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producttitle', models.CharField(db_column='productTitle', max_length=30)),
                ('productcost', models.IntegerField(db_column='productCost')),
                ('productowner', models.CharField(db_column='productOwner', max_length=30)),
            ],
            options={
                'db_table': 'modelforms_project',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
